esphome:
  name: walleaf
  friendly_name: Walleaf

esp8266:
  board: nodemcuv2

# Enable logging
logger:

# Enable Home Assistant API
api:
  password: ""
#  encryption:
#    key: "9BNM7l6pwjuXaCMwlr6n5wYZNa3moyP40OVHt6NKB88="

ota:
  - platform: esphome
    password: "2cdf2d6fa9d55e100dc9aed49eedaf41"

wifi:
  ssid: !secret kuba_ssid
  password: !secret kuba_password

  # Enable fallback hotspot (captive portal) in case wifi connection fails
  ap:
    ssid: "Walleaf Fallback Hotspot"
    password: "88GR0nZMtFna"

captive_portal:

# Photo sensor
sensor:
  - platform: adc
    id: light_sensor
    pin: A0
    name: "Walleaf Light Sensor"
    update_interval: 3s
    unit_of_measurement: ""
    filters:
    - round: 2 # Round to two decimal places 
    on_value:
      then:
        - light.turn_on: 
            id: walleaf_hex_1
            brightness: !lambda 'if (id(light_sensor).state > 0.15) { return x; } else if (true) { return 0.15; };'
        - light.turn_on: 
            id: walleaf_hex_2
            brightness: !lambda 'if (id(light_sensor).state > 0.15) { return x; } else if (true) { return 0.15; };'
        - light.turn_on: 
            id: walleaf_hex_3
            brightness: !lambda 'if (id(light_sensor).state > 0.15) { return x; } else if (true) { return 0.15; };'
        - light.turn_on: 
            id: walleaf_hex_4
            brightness: !lambda 'if (id(light_sensor).state > 0.15) { return x; } else if (true) { return 0.15; };'
        - light.turn_on: 
            id: walleaf_hex_5
            brightness: !lambda 'if (id(light_sensor).state > 0.15) { return x; } else if (true) { return 0.15; };'
        - light.turn_on: 
            id: walleaf_hex_6
            brightness: !lambda 'if (id(light_sensor).state > 0.15) { return x; } else if (true) { return 0.15; };'
        - light.turn_on: 
            id: walleaf_hex_7
            brightness: !lambda 'if (id(light_sensor).state > 0.15) { return x; } else if (true) { return 0.15; };'


# Buttons
binary_sensor:
  - platform: gpio
    pin:
      number: 14
      inverted: true
      mode:
        input: true
        pullup: true
    name: "Hex 1 btn"
    on_press:
      then:
        - light.turn_on: 
            id: walleaf_hex_1
            brightness: 100%
            transition_length: 0.2s
        - delay: 0.5s
        - light.turn_on: 
            id: walleaf_hex_1
            brightness: !lambda 'if (id(light_sensor).state > 0.15) { return id(light_sensor).state; } else if (true) { return 0.15; };'
            transition_length: 0.2s



  - platform: gpio
    pin:
      number: 12
      inverted: true
      mode:
        input: true
        pullup: true
    name: "Hex 2 btn"
    on_press:
      then:
        - light.turn_on: 
            id: walleaf_hex_2
            brightness: 100%
            transition_length: 0.2s
        - delay: 0.5s
        - light.turn_on: 
            id: walleaf_hex_2
            brightness: !lambda 'if (id(light_sensor).state > 0.15) { return id(light_sensor).state; } else if (true) { return 0.15; };'
            transition_length: 0.2s

  - platform: gpio
    pin:
      number: 4
      inverted: true
      mode:
        input: true
        pullup: true
    name: "Hex 3 btn"
    on_press:
      then:
        - light.turn_on: 
            id: walleaf_hex_3
            brightness: 100%
            transition_length: 0.2s
        - delay: 0.5s
        - light.turn_on: 
            id: walleaf_hex_3
            brightness: !lambda 'if (id(light_sensor).state > 0.15) { return id(light_sensor).state; } else if (true) { return 0.15; };'
            transition_length: 0.2s
            
  - platform: gpio
    pin:
      number: 0
      inverted: true
      mode:
        input: true
        pullup: true
    name: "Hex 4 btn"
    on_press:
      then:
        - light.turn_on: 
            id: walleaf_hex_4
            brightness: 100%
            transition_length: 0.2s
        - delay: 0.5s
        - light.turn_on: 
            id: walleaf_hex_4
            brightness: !lambda 'if (id(light_sensor).state > 0.15) { return id(light_sensor).state; } else if (true) { return 0.15; };'
            transition_length: 0.2s
            
  - platform: gpio
    pin:
      number: 2 # D4
      inverted: true
      mode:
        input: true
        pullup: true
    name: "Hex 5 btn"
    on_press:
      then:
        - light.turn_on: 
            id: walleaf_hex_5
            brightness: 100%
            transition_length: 0.2s
        - delay: 0.5s
        - light.turn_on: 
            id: walleaf_hex_5
            brightness: !lambda 'if (id(light_sensor).state > 0.15) { return id(light_sensor).state; } else if (true) { return 0.15; };'
            transition_length: 0.2s
            
  - platform: gpio
    pin:
      number: 10 # S3
      inverted: true
      mode:
        input: true
        pullup: true
    name: "Hex 6 btn"
    on_press:
      then:
        - light.turn_on: 
            id: walleaf_hex_6
            brightness: 100%
            transition_length: 0.2s
        - delay: 0.5s
        - light.turn_on: 
            id: walleaf_hex_6
            brightness: !lambda 'if (id(light_sensor).state > 0.15) { return id(light_sensor).state; } else if (true) { return 0.15; };'
            transition_length: 0.2s
            
  - platform: gpio
    pin:
      number: 9 # S2
      inverted: true
      mode:
        input: true
        pullup: true
    name: "Hex 7 btn"
    on_press:
      then:
        - light.turn_on: 
            id: walleaf_hex_7
            brightness: 100%
            transition_length: 0.2s
        - delay: 0.5s
        - light.turn_on: 
            id: walleaf_hex_7 
            brightness: !lambda 'if (id(light_sensor).state > 0.15) { return id(light_sensor).state; } else if (true) { return 0.15; };'
            transition_length: 0.2s


  # Switch
  - platform: gpio
    id: jumper_switch
    pin:
      number: 5
      inverted: true
      mode:
        input: true
        pullup: true
    name: "Switch"


# Lights
light:
  # Segment the light into 7 nodes
  - platform: partition
    id: walleaf_hex_1
    name: "Hex 1"
    segments:
      - id: walleaf
        from: 0
        to: 29
    effects:
      - addressable_rainbow:
      - addressable_rainbow:
          name: Rainbow Effect With Custom Values
          speed: 10
          width: 50

  - platform: partition
    id: walleaf_hex_2
    name: "Hex 2"
    segments:
      - id: walleaf
        from: 30
        to: 59
    effects:
      - addressable_rainbow:
      - addressable_rainbow:
          name: Rainbow Effect With Custom Values
          speed: 10
          width: 50

  - platform: partition
    id: walleaf_hex_3
    name: "Hex 3"
    segments:
      - id: walleaf
        from: 60
        to: 89
    effects:
      - addressable_rainbow:
      - addressable_rainbow:
          name: Rainbow Effect With Custom Values
          speed: 10
          width: 50

  - platform: partition
    id: walleaf_hex_4
    name: "Hex 4"
    segments:
      - id: walleaf
        from: 90
        to: 119
    effects:
      - addressable_rainbow:
      - addressable_rainbow:
          name: Rainbow Effect With Custom Values
          speed: 10
          width: 50

  - platform: partition
    id: walleaf_hex_5
    name: "Hex 5"
    segments:
      - id: walleaf
        from: 120
        to: 149
    effects:
      - addressable_rainbow:
      - addressable_rainbow:
          name: Rainbow Effect With Custom Values
          speed: 10
          width: 50

  - platform: partition
    id: walleaf_hex_6
    name: "Hex 6"
    segments:
      - id: walleaf
        from: 150
        to: 179
    effects:
      - addressable_rainbow:
      - addressable_rainbow:
          name: Rainbow Effect With Custom Values
          speed: 10
          width: 50

  - platform: partition
    id: walleaf_hex_7
    name: "Hex 7"
    segments:
      - id: walleaf
        from: 180
        to: 209
    effects:
      - addressable_rainbow:
      - addressable_rainbow:
          name: Rainbow Effect With Custom Values
          speed: 10
          width: 50

  # Configure the Walleaf itself
  - platform: neopixelbus
    id: walleaf
    type: GRB
    variant: ws2812x
    pin: 13
    num_leds: 210
    name: "Walleaf Hex"
    internal: true
    