esphome:
  name: walleaf
  friendly_name: Walleaf

esp8266:
  board: nodemcuv2

# Enable logging
logger:

# Enable Home Assistant API
api:
  encryption:
    key: "9BNM7l6pwjuXaCMwlr6n5wYZNa3moyP40OVHt6NKB88="

ota:
  - platform: esphome
    password: "2cdf2d6fa9d55e100dc9aed49eedaf41"

wifi:
  ssid: !secret wifi_ssid
  password: !secret wifi_password

  # Enable fallback hotspot (captive portal) in case wifi connection fails
  ap:
    ssid: "Walleaf Fallback Hotspot"
    password: "88GR0nZMtFna"

captive_portal:

# Photo sensor
sensor:
  - platform: adc
    id: light_sensor
    pin: A0
    name: "Walleaf Light Sensor"
    update_interval: 10s
    unit_of_measurement: ""
    filters:
    - round: 2 # Round to two decimal places 
    on_value:
      then:
        - light.turn_on: 
            id: walleaf_hex_1
            brightness: !lambda 'if (id(light_sensor).state > 0.1) { return x; } else { return 0.15; };'
        - light.turn_on: 
            id: walleaf_hex_2
            brightness: !lambda 'if (id(light_sensor).state > 0.1) { return x; } else { return 0.15; };'
        - light.turn_on: 
            id: walleaf_hex_3
            brightness: !lambda 'if (id(light_sensor).state > 0.1) { return x; } else { return 0.15; };'


# Buttons
binary_sensor:
  - platform: gpio
    pin:
      number: 14
      inverted: true
      mode:
        input: true
        pullup: true
    name: "Hex 1 btn"
    on_press:
      then:
        - light.turn_on: 
            id: walleaf_hex_1
            brightness: 100%
            transition_length: 0.2s
        - delay: 0.5s
        - light.turn_on: 
            id: walleaf_hex_1
            brightness: 15%
            transition_length: 0.2s



  - platform: gpio
    pin:
      number: 12
      inverted: true
      mode:
        input: true
        pullup: true
    name: "Hex 2 btn"
    on_press:
      then:
        - light.turn_on: 
            id: walleaf_hex_2
            brightness: 100%
            transition_length: 0.2s
        - delay: 0.5s
        - light.turn_on: 
            id: walleaf_hex_2
            brightness: 15%
            transition_length: 0.2s


# Lights
light:
  # Segment the light into 3 nodes
  - platform: partition
    id: walleaf_hex_1
    name: "Hex 1"
    segments:
      - id: walleaf
        from: 0
        to: 29
    effects:
      - addressable_rainbow:
      - addressable_rainbow:
          name: Rainbow Effect With Custom Values
          speed: 10
          width: 50

  - platform: partition
    id: walleaf_hex_2
    name: "Hex 2"
    segments:
      - id: walleaf
        from: 30
        to: 59
    effects:
      - addressable_rainbow:
      - addressable_rainbow:
          name: Rainbow Effect With Custom Values
          speed: 10
          width: 50

  - platform: partition
    id: walleaf_hex_3
    name: "Hex 3"
    segments:
      - id: walleaf
        from: 60
        to: 89
    effects:
      - addressable_rainbow:
      - addressable_rainbow:
          name: Rainbow Effect With Custom Values
          speed: 10
          width: 50

  # Configure the Walleaf itself
  - platform: neopixelbus
    id: walleaf
    type: GRB
    variant: ws2812x
    pin: 13
    num_leds: 90
    name: "Walleaf Hex"
    internal: true
    