esphome:
  name: uwu

esp8266:
  board: nodemcuv2

# Enable logging
logger:

# Enable Home Assistant API
api:
  password: ""

ota:
  - platform: esphome
    password: ""

wifi:
  ssid: "Wifi_2_2,4GHz"
  password: "20405380"

  # Enable fallback hotspot (captive portal) in case wifi connection fails
  ap:
    ssid: "Uwu Fallback Hotspot"
    password: "IDbXsRowLX6R"

captive_portal:
    